
PPE_MODEL_PATH = r"Z:/AI PROJECTS/PPE Detection/LivePPE/yolov11_large.pt"
FACE_DB_PATH = r"Z:/AI PROJECTS/PPE Detection/Datasets/face_data"

CAMERA_INDEX = 0  

FACE_RECOGNITION_INTERVAL = 30  # Run every N frames (30 = ~1 second at 30 FPS)

PPE_CONFIDENCE_THRESHOLD = 0.3  # Lowered from 0.5 for better detection
FACE_DETECTION_CONFIDENCE = 0.5
FACE_SIMILARITY_THRESHOLD = 0.7

VIOLATION_COOLDOWN_MINUTES = 5 
LOG_UNKNOWN_VIOLATIONS = False 
